using Dualization
using JuMP
using Gurobi
using MathOptInterface

include("helper_functions.jl")

# --- Setup ---
T    = vcat(651)
data = load_data("poc")
net  = build_network(data)
gen  = build_generators(data, T, net.bus_to_idx)

(; BUS, LINE, N, L, PTDF, Fmax, bus_to_idx) = net
(; I, vc, cap, tech, gens, fc, a, alpha)     = gen


WTP       = 100
D_max     = Dict(t => Float64(data.dem_tot_df.load[t]) for t in T)
snapshots = Vector{String}(data.dem_df.snapshot)
d_max     = zeros(nrow(data.dem_df), length(BUS))
for (n_idx, bus_name) in enumerate(BUS)
    d_max[:, n_idx] = Float64.(data.dem_df[!, bus_name])
end

d_nodal = Dict((t, bus) => data.dem_df[data.dem_df.snapshot .== snapshots[t], bus][1] / D_max[t] for t in T, bus in BUS)
# for any t, d_nodal has to sum to 1
for t in T
    @assert sum(d_nodal[(t, bus)] for bus in BUS) ≈ 1 "Nodal demand shares do not sum to 1 for time $t"
end

PEN = 100000.0 # penalty for curtailment in redispatch

# --- Generator → bus mapping ---
gen_bus_idx = Dict(i => bus_to_idx[gens[i]] for i in I)


q_max = Dict((t, i) => cap[i] for t in T, i in I) # available capacity of generator i at time t

q_max_inf = Dict((t, i) => 0.0 for t in T, i in I) # available capacity of generator i at time t
q_max_inf[(651, "NL0 0 coal")] = 200
q_max_inf[(651, "NL0 1 coal")] = 0.0
q_max_inf[(651, "NL0 10 coal")] = 95.0

q = Dict((t, i) => 0.0 for t in T, i in I) # power generated by generator i at time t
q[(651, "NL0 0 coal")] = 40.0
q[(651, "NL0 1 coal")] = 0.0
q[(651, "NL0 10 coal")] = 95.0

lambda_e = 5.0 # market price at time t

m_rd = Model(Gurobi.Optimizer)

nodal_demand = @expression(m_rd, d[t in T, n in N], d_nodal[(t, BUS[n])] * D_max[t]) # nodal demand at time t and node n
curtailment = @variable(m_rd, curt[t in T, n in N] >= 0) # curtailment at node n at time t
red_pos = @variable(m_rd, r_up[t in T, i in I] >= 0) # upward redispatch provided by generator i at time t
red_neg = @variable(m_rd, r_down[t in T, i in I] >= 0) # downward redispatch provided by generator i at time t
power_flow = @variable(m_rd, p_flow[t in T, l in L]) # power flow on line l at time t
power_inj = @expression(m_rd, p_inj[t in T, n in N], sum(q[t, i] for i in I if gen_bus_idx[i] == n)+ sum(r_up[t, i] - r_down[t, i] for i in I if gen_bus_idx[i] == n) - (d[t, n] - curt[t, n])) # power injected at node n at time t

red_pos_up = @constraint(m_rd, red_pos_up[t in T, i in I], r_up[t, i] - q_max[t, i] + q[t, i] <= 0) # upward redispatch cannot exceed remaining capacity
red_neg_up = @constraint(m_rd, red_neg_up[t in T, i in I], r_down[t, i] - q[t, i] <= 0) # downward redispatch cannot exceed current generation
curt_up = @constraint(m_rd, curt_up[t in T, n in N], curt[t, n] - d[t, n] <= 0) # curtailment cannot exceed demand
redispatch_balance = @constraint(m_rd, redispatch_balance[t in T], sum(r_up[t,i] - r_down[t,i] for i in I) == 0) # total redispatch must be zero at time t
thermal_limit_up = @constraint(m_rd, thermal_limit_up[t in T, l in L], p_flow[t, l] - Fmax[l] <= 0) # flow on line l cannot exceed capacity in positive direction
thermal_limit_low = @constraint(m_rd, thermal_limit_low[t in T, l in L], -Fmax[l] - p_flow[t, l] <= 0) # flow on line l cannot exceed capacity in negative direction
flow_definition = @constraint(m_rd, flow_definition[t in T, l in L], p_flow[t, l] - sum(PTDF[l, n] * p_inj[t, n] for n in N) == 0) # power flow on line l at time t



@objective(m_rd, Min, sum(sum(vc[i] * r_up[t, i] + (vc[i] - lambda_e) * r_down[t, i] for i in I) + PEN * sum(curt[t, n] for n in N) for t in T))
optimize!(m_rd)

dual_rd = dualize(m_rd; dual_names = DualNames("dual_var_", "dual_constr_"))
print(dual_rd)
set_optimizer(dual_rd, Gurobi.Optimizer)
optimize!(dual_rd)

for i in I
    n = gen_bus_idx[i]
    println(i, " at node ", n, ": PTDF column = ", [PTDF[l,n] for l in L])
end

p_flow_market = Dict((t, l) => sum(PTDF[l, n] * 
            (sum(q[t, i] for i in I if gen_bus_idx[i] == n; init=0.0) - d[t, n])
            for n in N)
            for t in T, l in L)

d_rd = Model(Gurobi.Optimizer)

dual_red_pos_up = @variable(d_rd, beta_pos_up[t in T, i in I] <= 0)
dual_red_pos_low = @variable(d_rd, beta_pos_low[t in T, i in I] <= 0)
dual_red_neg_up = @variable(d_rd, beta_neg_up[t in T, i in I] <= 0)
dual_red_neg_low = @variable(d_rd, beta_neg_low[t in T, i in I] <= 0)
dual_curt_up = @variable(d_rd, beta_curt_up[t in T, n in N] <= 0)
dual_red_balance = @variable(d_rd, lambda_rd[t in T])
dual_thermal_up = @variable(d_rd, rho_up[t in T, l in L] <= 0)
dual_thermal_low = @variable(d_rd, rho_low[t in T, l in L] <= 0)
dual_p_flow = @variable(d_rd, phi[t in T, l in L]) # dual variable for power flow constraint

dual_feas_r_up = @constraint(d_rd, dual_feas_r_up[t in T, i in I], vc[i] - lambda_rd[t] - beta_pos_up[t, i]  + sum(PTDF[l, gen_bus_idx[i]] * phi[t, l] for l in L) >= 0) # dual feasibility for upward redispatch
dual_feas_r_down = @constraint(d_rd, dual_feas_r_down[t in T, i in I], lambda_e - vc[i] + lambda_rd[t] - beta_neg_up[t, i]  - sum(PTDF[l, gen_bus_idx[i]] * phi[t, l] for l in L) >= 0) # dual feasibility for downward redispatch
dual_feas_thermal_limit = @constraint(d_rd, dual_feas_thermal_limit[t in T, l in L], phi[t, l] + rho_up[t, l] - rho_low[t, l] == 0) # dual feasibility for thermal limit constraint
dual_feas_curt = @constraint(d_rd, dual_feas_curt[t in T, n in N], PEN - beta_curt_up[t, n] + sum(PTDF[l, n] * phi[t, l] for l in L) >= 0) # dual feasibility for curtailment constraint

@objective(d_rd, Max, sum(
      sum((q_max[t,i] - q[t,i]) * beta_pos_up[t,i] for i in I)
    + sum(q[t,i] * beta_neg_up[t,i] for i in I)
    + sum(d_nodal[(t, BUS[n])] * D_max[t] * beta_curt_up[t, n] for n in N)
    + sum(Fmax[l] * rho_up[t,l]  for l in L)
    + sum(Fmax[l] * rho_low[t,l] for l in L)        
    + sum(p_flow_market[t, l] * phi[t, l] for l in L) for t in T))


optimize!(d_rd)

print(d_rd)

println("Dual objective: ", objective_value(d_rd))
println("Dual model objective: ", objective_value(dual_rd))
println("Primal objective: ", objective_value(m_rd))


#--- Infeasable redispatch check (curtailment)---

m_rd_inf = Model(Gurobi.Optimizer)

curtailment = @variable(m_rd_inf, curt[t in T, n in N] >= 0) # curtailment at node n at time t
nodal_demand = @expression(m_rd_inf, d[t in T, n in N], d_nodal[(t, BUS[n])] * D_max[t]) # nodal demand at time t and node n
red_pos = @variable(m_rd_inf, r_up[t in T, i in I] >= 0) # upward redispatch provided by generator i at time t
red_neg = @variable(m_rd_inf, r_down[t in T, i in I] >= 0) # downward redispatch provided by generator i at time t
power_flow = @variable(m_rd_inf, p_flow[t in T, l in L]) # power flow on line l at time t
power_inj = @expression(m_rd_inf, p_inj[t in T, n in N], sum(q[t, i] for i in I if gen_bus_idx[i] == n)+ sum(r_up[t, i] - r_down[t, i] for i in I if gen_bus_idx[i] == n) - d[t, n] + curt[t, n]) # power injected at node n at time t

red_pos_up = @constraint(m_rd_inf, red_pos_up[t in T, i in I], r_up[t, i] - q_max_inf[t, i] + q[t, i] <= 0) # upward redispatch cannot exceed remaining capacity
red_neg_up = @constraint(m_rd_inf, red_neg_up[t in T, i in I], r_down[t, i] - q[t, i] <= 0) # downward redispatch cannot exceed current generation
curt_up = @constraint(m_rd_inf, curt_up[t in T, n in N], curt[t, n] - d[t, n] <= 0) # curtailment cannot exceed demand
redispatch_balance = @constraint(m_rd_inf, redispatch_balance[t in T], sum(r_up[t,i] - r_down[t,i] for i in I) == 0) # total redispatch must be zero at time t
thermal_limit_up = @constraint(m_rd_inf, thermal_limit_up[t in T, l in L], p_flow[t, l] - Fmax[l] <= 0) # flow on line l cannot exceed capacity in positive direction
thermal_limit_low = @constraint(m_rd_inf, thermal_limit_low[t in T, l in L], -Fmax[l] - p_flow[t, l] <= 0) # flow on line l cannot exceed capacity in negative direction
flow_definition = @constraint(m_rd_inf, flow_definition[t in T, l in L], p_flow[t, l] - sum(PTDF[l, n] * p_inj[t, n] for n in N) == 0) # power flow on line l at time t


@objective(m_rd_inf, Min, sum(sum(vc[i] * r_up[t, i] + (vc[i] - lambda_e) * r_down[t, i] for i in I) + PEN * sum(curt[t, n] for n in N) for t in T))
optimize!(m_rd_inf)

# check results
for t in T
    for n in N
        println("nodal demand: ", value(d[t, n]))
        println("curtailment: ", value(curt[t, n]))
    end
end

dual_rd_inf = dualize(m_rd_inf; dual_names = DualNames("dual_var_", "dual_constr_"))
set_optimizer(dual_rd_inf, Gurobi.Optimizer)
optimize!(dual_rd_inf)
print(dual_rd_inf)

d_rd_inf = Model(Gurobi.Optimizer)

nodal_demand = @expression(d_rd_inf, d[t in T, n in N], d_nodal[(t, BUS[n])] * D_max[t]) # nodal demand at time t and node n
power_inj = @expression(d_rd_inf, p_inj[t in T, n in N], sum(q[t, i] for i in I if gen_bus_idx[i] == n)+ sum(r_up[t, i] - r_down[t, i] for i in I if gen_bus_idx[i] == n) - d[t, n] + curt[t, n]) # power injected at node n at time t

dual_red_pos_up = @variable(d_rd_inf, beta_pos_up[t in T, i in I] <= 0)
dual_red_pos_low = @variable(d_rd_inf, beta_pos_low[t in T, i in I] <= 0)
dual_red_neg_up = @variable(d_rd_inf, beta_neg_up[t in T, i in I] <= 0)
dual_red_neg_low = @variable(d_rd_inf, beta_neg_low[t in T, i in I] <= 0)
dual_curt_up = @variable(d_rd_inf, beta_curt_up[t in T, n in N] <= 0)
dual_red_balance = @variable(d_rd_inf, lambda_rd[t in T])
dual_thermal_up = @variable(d_rd_inf, rho_up[t in T, l in L] <= 0)
dual_thermal_low = @variable(d_rd_inf, rho_low[t in T, l in L] <= 0)
dual_p_flow = @variable(d_rd_inf, phi[t in T, l in L]) # dual variable for power flow constraint

dual_feas_r_up = @constraint(d_rd_inf, dual_feas_r_up[t in T, i in I], vc[i] - lambda_rd[t] - beta_pos_up[t, i]  + sum(PTDF[l, gen_bus_idx[i]] * phi[t, l] for l in L) >= 0) # dual feasibility for upward redispatch
dual_feas_r_down = @constraint(d_rd_inf, dual_feas_r_down[t in T, i in I], lambda_e - vc[i] + lambda_rd[t] - beta_neg_up[t, i]  - sum(PTDF[l, gen_bus_idx[i]] * phi[t, l] for l in L) >= 0) # dual feasibility for downward redispatch
dual_feas_thermal_limit = @constraint(d_rd_inf, dual_feas_thermal_limit[t in T, l in L], phi[t, l] + rho_up[t, l] - rho_low[t, l] == 0) # dual feasibility for thermal limit constraint
dual_feas_curt = @constraint(d_rd_inf, dual_feas_curt[t in T, n in N], PEN - beta_curt_up[t, n] + sum(PTDF[l, n] * phi[t, l] for l in L) >= 0) # dual feasibility for curtailment constraint

@objective(d_rd_inf, Max, sum(
      sum((q_max_inf[t,i] - q[t,i]) * beta_pos_up[t,i] for i in I)
    + sum(q[t,i] * beta_neg_up[t,i] for i in I)
    + sum(d[t, n] * beta_curt_up[t, n] for n in N)
    + sum(Fmax[l] * rho_up[t,l]  for l in L)
    + sum(Fmax[l] * rho_low[t,l] for l in L)
    + sum(p_flow_market[t, l] * phi[t, l] for l in L) for t in T))

optimize!(d_rd_inf)

println("Dual objective: ", objective_value(d_rd_inf))
println("Dual model objective: ", objective_value(dual_rd_inf))
println("Primal objective: ", objective_value(m_rd_inf))


