using JuMP
using CSV
using DataFrames
using Gurobi
using MathOptInterface
using PATHSolver
using Latexify

gen_df = CSV.read("data/nl20_generators.csv", DataFrame)
#gen_df = CSV.read("data/nl20_controllable_generators.csv", DataFrame)
renewable_df = CSV.read("data/nl20_renewable_generators.csv", DataFrame)
dem_tot_df = CSV.read("data/nl20_total_load_timeseries.csv", DataFrame)
dem_df = CSV.read("data/nl20_load_timeseries_per_bus.csv", DataFrame)
ptdf_df = CSV.read("data/ptdf_matrix.csv", DataFrame)
bus_order_df = CSV.read("data/bus_order.csv", DataFrame)
line_order_df = CSV.read("data/line_order.csv", DataFrame)
fixed_om_df = CSV.read("data/fixed_om_costs.csv", DataFrame)
cf_df = CSV.read("data/nl20_renewable_cf_per_generator.csv", DataFrame)

BUS = string.(bus_order_df.name)
LINE = string.(line_order_df.name)

bus_to_idx  = Dict(BUS[i] => i for i in eachindex(BUS))
line_to_idx = Dict(LINE[i] => i for i in eachindex(LINE))

ptdf_bus_names  = string.(names(ptdf_df)[2:end])
ptdf_line_names = string.(ptdf_df[:, 1])

# Check that ordering of buses and lines in PTDF matches bus_order.csv and line_order.csv
@assert ptdf_line_names == LINE "Line order in PTDF does not match line_order.csv"
@assert collect(ptdf_bus_names) == BUS "Bus order in PTDF does not match bus_order.csv"
cf_df.var"snapshot"
PTDF = Matrix{Float64}(ptdf_df[:, 2:end])
Fmax = Vector{Float64}(line_order_df.s_nom)
T = 2809:2860 # few hours for testing
hours = length(T)
vc   = Dict(row.name => row.marginal_cost for row in eachrow(gen_df))
cap = Dict(row.name => row.p_nom for row in eachrow(gen_df))
tech = Dict(row.name => row.carrier for row in eachrow(gen_df))
gens = Dict(row.name => row.bus for row in eachrow(gen_df))
I = Vector{String}(gen_df.name)

fc = Dict(row.tech => (row.fixed_om_eur_MW_hour * hours) for row in eachrow(fixed_om_df))
# Add missing technologies with default 0.0
for t in unique(values(tech))
    if !haskey(fc, t)
        fc[t] = 0.0
    end
end
WTP   = 100
D_max = Dict(t => Float64(dem_tot_df.load[t]) for t in T)
N = 1:length(BUS)
L = 1:length(LINE)
timeseries = dem_tot_df.snapshot
snapshots = Vector{String}(dem_tot_df.snapshot)
T_full = 1:nrow(dem_tot_df)
T_nodal_demand = 1:nrow(dem_df)
d_max = zeros(length(T_nodal_demand), length(BUS))
for (n_idx, bus_name) in enumerate(BUS)
    d_max[:, n_idx] = Float64.(dem_df[!, bus_name])
end
snapshots = Vector{String}(dem_df.snapshot)
gen_df.bus_idx = [bus_to_idx[n] for n in gen_df.bus]
first(gen_df[:, [:name, :bus, :bus_idx]], 10)
gen_bus_idx = Dict(row.name => row.bus_idx for row in eachrow(gen_df))
PTDF[[first(L)], gen_bus_idx[first(I)]]
renewables_in_model = Set(renewable_df.name)
# availability factor for all generators
# For each timestep t in T, map to corresponding row in cf_df
a = Dict()
for (idx, t) in enumerate(T_full)
    for i in I
        if i in names(cf_df)
            a[(t, i)] = Float64(cf_df[t, i])
        else
            a[(t, i)] = 1.0  # Non-renewables get full availability
        end
    end
end

# check if values from renewable cf dataframe and dictionary match
for (t, i) in keys(a)
    if i in names(cf_df)
        @assert a[(t, i)] == Float64(cf_df[t, i]) "Mismatch in availability factor for generator $i at time $t"
    else
        @assert a[(t, i)] == 1.0 "Non-renewable generator $i should have availability factor of 1.0"
    end
end

# capacity-market derating factors: renewables cannot bid capacity
renewable_carriers = Set(["onwind", "offwind-ac", "solar"])
alpha = Dict(i => in(tech[i], renewable_carriers) ? 0.0 : 1.0 for i in keys(tech))

# highest residual load within selected hours for capacity demand
resid_load = Dict(
    t => D_max[t] - sum(cap[i] * a[(t, i)] for i in renewables_in_model)
    for t in T
)

d_c = max(0.0, maximum(values(resid_load))) # capacity demand must be non-negative
m = Model(Gurobi.Optimizer)

# Generator block
power = @variable(m, q[t in T, i in I]) # power generated by generator g at time t
cm_offer =@variable(m, c_cm[i in I] ) # capacity offered in capacity market
disinvest = @variable(m, c[i in I]) # capacity of generator i to be kept

#cap_eff = @expression(m, cap_eff[i in I], cap[i] - c_dis[i]) # effective installed capacity after disinvestment
gen_max = @expression(m, q_max[t in T, i in I], c[i] * a[(t, i)]) # available capacity of generator i at time t
cm_max = @expression(m, cap_max_cm[i in I], alpha[i] * c[i]) # maximum capacity offer in capacity market for generator i

gen_up = @constraint(m, [t in T, i in I], q[t, i] - q_max[t, i]<= 0) # max generation limit
dual_gen_up = @variable(m, mu_g_up[t in T, i in I] >= 0)

gen_low = @constraint(m, [t in T, i in I], -q[t, i] <= 0) # min generation limit
dual_gen_low = @variable(m, mu_g_low[t in T, i in I] >= 0)

cap_cm_up = @constraint(m, [i in I], c_cm[i] - cap_max_cm[i]<= 0) # capacity market limit
dual_cap_cm_up = @variable(m, mu_cm_up[i in I] >= 0) # dual variable for capacity market limit

cap_cm_low = @constraint(m, [i in I], -c_cm[i] <= 0) # capacity market lower bound
dual_cap_cm_low = @variable(m, mu_cm_low[i in I] >= 0) # dual variable for capacity market lower bound

dis_up = @constraint(m, [i in I], c[i] <= cap[i]) # capacity to be kept cannot exceed existing capacity
dual_dis_up = @variable(m, mu_dis_up[i in I] >= 0) # dual variable for disinvestment upper bound

dis_low = @constraint(m, [i in I], - c[i] <= 0) # capacity to be kept cannot be negative
dual_dis_low = @variable(m, mu_dis_low[i in I] >= 0) # dual variable for disinvestment lower bound

market_clearing = @constraint(m, [t in T], sum(q[t, i] for i in I) == D_max[t]) # supply-demand balance at time t
lambda_e_lb = 0
lambda_e_ub = 150
dual_market_clearing = @variable(m, lambda_e_lb <= lambda_e[t in T] <= lambda_e_ub) # price for energy at time t

capacity_clearing = @constraint(m, sum(c_cm[i] for i in I) == d_c) # capacity requirement must be met at time t
lambda_c_lb = 0
lambda_c_ub = maximum(values(fc[tech[i]] for i in I)) # upper bound for capacity price based on maximum possible disinvestment cost
dual_capacity_clearing = @variable(m, lambda_c_lb <= lambda_c <= lambda_c_ub) # price for capacity at time t

dual_feas_gen = @constraint(m, [t in T, i in I], lambda_e[t] - vc[i] + mu_g_low[t, i] - mu_g_up[t, i] == 0) # dual feasibility for generation
dual_feas_cm = @constraint(m, [i in I], lambda_c + mu_cm_low[i] - mu_cm_up[i] == 0) # dual feasibility for capacity market
dual_feas_dis = @constraint(m, [i in I], -fc[tech[i]] + mu_dis_low[i] - mu_dis_up[i] + sum(mu_g_up[t, i] * a[(t, i)] for t in T) + mu_cm_up[i] * alpha[i]== 0) # dual feasibility for disinvestment 

strong_dual_gen = @constraint(m, [i in I],
    sum((lambda_e[t] - vc[i]) * q[t, i] for t in T) - fc[tech[i]] * c[i] + lambda_c * c_cm[i] ==
    mu_dis_up[i] * cap[i]
 ) # strong duality: only nonzero primal RHS contributes to the dual objective

# Redispatch block
red_pos = @variable(m, r_up[t in T, i in I]) # upward redispatch provided by generator i at time t
red_neg = @variable(m, r_down[t in T, i in I]) # downward redispatch provided by generator i at time t
power_flow = @variable(m, p_flow[t in T, l in L]) # power flow on line l at time t
power_inj = @expression(m, p_inj[t in T, n in N], sum(q[t, i] for i in I if gen_bus_idx[i] == n)+ sum(r_up[t, i] - r_down[t, i] for i in I if gen_bus_idx[i] == n) - d_max[t,n]) # power injected at node n at time t

red_pos_up = @constraint(m, [t in T, i in I], r_up[t, i] - q_max[t, i] + q[t, i] <= 0) # upward redispatch cannot exceed remaining capacity
#dual_red_pos_up = @variable(m, beta_pos_up[t in T, i in I] <= 0)

red_pos_low = @constraint(m, [t in T, i in I], -r_up[t, i] <= 0) # upward redispatch cannot be negative
#dual_red_pos_low = @variable(m, beta_pos_low[t in T, i in I] <= 0)

red_neg_up = @constraint(m, [t in T, i in I], r_down[t, i] - q[t, i] <= 0) # downward redispatch cannot exceed current generation
#dual_red_neg_up = @variable(m, beta_neg_up[t in T, i in I] <= 0)

red_neg_low = @constraint(m, [t in T, i in I], -r_down[t, i] <= 0) # downward redispatch cannot be negative
#dual_red_neg_low = @variable(m, beta_neg_low[t in T, i in I] <= 0)

redispatch_balance = @constraint(m, [t in T], sum(r_up[t,i] - r_down[t,i] for i in I) == 0) # total redispatch must be zero at time t
#dual_red_balance = @variable(m, lambda_rd[t in T])

thermal_limit_up = @constraint(m, [t in T, l in L], p_flow[t, l] - Fmax[l] <= 0) # flow on line l cannot exceed capacity in positive direction
#dual_thermal_up = @variable(m, rho_up[t in T, l in L] <= 0)

thermal_limit_low = @constraint(m, [t in T, l in L], -Fmax[l] - p_flow[t, l] <= 0) # flow on line l cannot exceed capacity in negative direction
#dual_thermal_low = @variable(m, rho_low[t in T, l in L] <= 0)

flow_definition = @constraint(m, [t in T, l in L], p_flow[t, l] - sum(PTDF[l, n] * p_inj[t, n] for n in N) == 0) # power flow on line l at time t
#dual_p_flow = @variable(m, phi[t in T, l in L]) # dual variable for power flow constraint

#dual_feas_r_up = @constraint(m, [t in T, i in I], vc[i] + lambda_rd[t] + beta_pos_up[t, i] - beta_pos_low[t, i] - sum(PTDF[l, gen_bus_idx[i]] * phi[t, l] for l in L) == 0) # dual feasibility for upward redispatch
#dual_feas_r_down = @constraint(m, [t in T, i in I], vc[i] - lambda_rd[t] + beta_neg_up[t, i] - beta_neg_low[t, i] + sum(PTDF[l, gen_bus_idx[i]] * phi[t, l] for l in L) == 0) # dual feasibility for downward redispatch
#dual_feas_thermal_limit = @constraint(m, [t in T, l in L], phi[t, l] + rho_up[t, l] - rho_low[t, l] == 0) # dual feasibility for thermal limit constraint

#strong_dual_redispatch = @constraint(m, [t in T],
    #sum(vc[i] * (r_up[t, i] + r_down[t, i]) for i in I) ==
    #sum(beta_pos_up[t, i] * (q_max[t, i] - q[t, i]) for i in I) +
    #sum(beta_neg_up[t, i] * q[t, i] for i in I) +
    #sum(rho_up[t, l] * Fmax[l] + rho_low[t, l] * Fmax[l] for l in L)
 # strong duality for redispatch at time t

# Demand block


#@variable(m, mu_D_low[t in T] >= 0) # dual variable for D[t] >= 0, incl dual constraint
#@variable(m, mu_D_up[t in T] >= 0) # dual variable for D[t] <= D_max[t], incl dual constraint

#@expression(m, D[t in T], sum(d[t in T, n in N] for n in N)) # aggregate load at time t
#@expression(m, D[t in T], sum(d_max[t, n] for n in N)) # aggregate load at time t, using data instead of decision variables for testing


#@constraint(m, [t in T], D[t] <= D_max[t]) # max demand limit
#@constraint(m, [t in T], D_max[t] == sum(d_max[t, n] for n in N)) # sum of nodal demands equals aggregate demand at time t
#@constraint(m, [t in T], lambda_e[t]- WTP == mu_D_up[t] - mu_D_low[t]) # dual feasibility
#@constraint(m, [t in T], (lambda_e[t] - WTP) * D_max[t] == D_max[t] * mu_D_up[t]) # strong duality constraint for demand at time t

# objective: system-level redispatch objective only
@objective(m, Min, sum(vc[i] * (r_up[t, i] + r_down[t, i]) for t in T, i in I)) # minimize redispatch cost
# social welfare maximization objective
#@objective(m, Max, sum(lambda_e[t] * D_max[t] - sum(vc[i] * q[t, i] for i in I) for t in T))

set_optimizer_attribute(m, "TimeLimit", 700)   
set_optimizer_attribute(m, "NonConvex", 2)
set_optimizer_attribute(m, "FeasibilityTol", 1e-5)
set_optimizer_attribute(m, "DualReductions", 0)
set_optimizer_attribute(m, "IISMethod", 1)  # Optional, chooses IIS algorithm
optimize!(m)

const MOI = MathOptInterface

println("Termination status: ", termination_status(m))

if termination_status(m) == MOI.OPTIMAL
    println("Redispatch objective: ", objective_value(m))
    println("Capacity requirement (max residual load): ", d_c)

    for i in I
        kept_capacity = value(disinvest[i])
        retired_capacity = cap[i] - kept_capacity
        println(i,
            " initial cap = ", cap[i],
            " kept cap = ", kept_capacity,
            " retired cap = ", retired_capacity,
            " q = ", max(value(q[t, i]) for t in T),
            " r_up = ", max(value(r_up[t, i]) for t in T),
            " r_down = ", max(value(r_down[t, i]) for t in T))
    end

    for l in L
        println("Line ", l,
            " flow = ", max(value(p_flow[t, l]) for t in T),
            " / limit = ", Fmax[l])
    end
    for t in T
        println("Price at time ", t, ": ", value(lambda_e[t]))
        println("Capacity price: ", value(lambda_c))
        
    end
    for t in T 
        println("Total up redispatch at time ", t, ": ", sum(value.(r_up[t, i] for i in I )))
    end
    for t in T 
        println("Total downwards redispatch at time ", t, ": ", sum(value.(r_down[t, i] for i in I )))
    end

    if sum(value.(r_up[t, i]) - value.(r_down[t, i]) for t in T, i in I) == 0
        println("Net redispatch is zero at optimality, as expected.")
    else
        println("Warning: Net redispatch is not zero at optimality, which may indicate an issue with the model.")
    end

    # installed and retired capacities
    total_initial_capacity = sum(cap[i] for i in I; init = 0.0)
    total_kept_capacity = sum(value(disinvest[i]) for i in I; init = 0.0)
    total_retired_capacity = sum(cap[i] - value(disinvest[i]) for i in I; init = 0.0)
    println("Total initial capacity: ", total_initial_capacity)
    println("Total kept capacity: ", total_kept_capacity)
    println("Total retired capacity: ", total_retired_capacity)

    tech_labels = Dict(
        "CCGT" => "CCGT",
        "biomass" => "Biomass",
        "onwind" => "Onshore Wind",
        "offwind-ac" => "Offshore Wind",
        "waste" => "Waste",
        "nuclear" => "Nuclear"
    )

    for n in N
        node_kept_capacity = sum(value(disinvest[i]) for i in I if gen_bus_idx[i] == n; init = 0.0)
        println("Node ", n, " kept capacity: ", node_kept_capacity)

        for t_name in keys(tech_labels)
            if any(i -> gen_bus_idx[i] == n && tech[i] == t_name, I)
                node_tech_kept_cap = sum(value(disinvest[i]) for i in I if gen_bus_idx[i] == n && tech[i] == t_name; init = 0.0)
                println("  ", tech_labels[t_name], ": ", node_tech_kept_cap)
            end
        end
    end

end

if termination_status(m) == MOI.INFEASIBLE
    set_optimizer_attribute(m, "TimeLimit", 700)  
    compute_conflict!(m) 
    println("Conflict status: ", get_attribute(m, MOI.ConflictStatus()))
end

for (func_type, set_type) in list_of_constraint_types(m)
    for c in all_constraints(m, func_type, set_type)
        if MOI.get(m, MOI.ConstraintConflictStatus(), c) == MOI.IN_CONFLICT
            println("Infeasible constraint: ", c)
        end
    end
end
for v in all_variables(m)
    if MOI.get(m, MOI.VariableConflictStatus(), v) == MOI.IN_CONFLICT
        println("Infeasible variable: ", v)
    end
end